// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzkT-9TGSSt04YGr-20vYX8J4IPvtJe3c',
    appId: '1:504655666989:web:8453a9fa4bf4e10e95bda4',
    messagingSenderId: '504655666989',
    projectId: 'bmoovddatabase',
    authDomain: 'bmoovddatabase.firebaseapp.com',
    storageBucket: 'bmoovddatabase.appspot.com',
    measurementId: 'G-J16V451BYK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAysG4SzzV0BRAMnnmmwb2_ibKKNIIDtBI',
    appId: '1:504655666989:android:19c985f900a372d595bda4',
    messagingSenderId: '504655666989',
    projectId: 'bmoovddatabase',
    storageBucket: 'bmoovddatabase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQQwYG4-kiWZq4YobWMe0Tr1DVOCAPenQ',
    appId: '1:504655666989:ios:55907dad845d86ad95bda4',
    messagingSenderId: '504655666989',
    projectId: 'bmoovddatabase',
    storageBucket: 'bmoovddatabase.appspot.com',
    iosBundleId: 'com.example.bmoovd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzkT-9TGSSt04YGr-20vYX8J4IPvtJe3c',
    appId: '1:504655666989:web:8ec36ba04153f8f295bda4',
    messagingSenderId: '504655666989',
    projectId: 'bmoovddatabase',
    authDomain: 'bmoovddatabase.firebaseapp.com',
    storageBucket: 'bmoovddatabase.appspot.com',
    measurementId: 'G-XP3CGKK2FF',
  );
}
